version: "3.9"

services:
  server:
    build: ./src/
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server